sudo: false
dist: trusty
os: osx
language: rust
cache: cargo
rust:
  - nightly
branches:
  only:
  - master 
#before_script:
  #- (cargo install mdbook --vers 0.1.7 --force || true)
#  - mkdir -p tmp
#  - git clone xxx - tmpx/xx
#  - cmp_hash tmp/xx 2018-edition
script:
  - ./tools/mdbook build
deploy:
  provider: pages
  local-dir: book
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  project_name: "Crystal 编程语言（中文版）"
  keep-history: false
  on:
    branch: master
